//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant
    {
        public int Act_id { get; set; }
        public string Act_name { get; set; }
        public string Act_LName { get; set; }
        public Nullable<int> Act_age { get; set; }
        public Nullable<int> working_time { get; set; }
        public string Address { get; set; }
        public string mobile_number { get; set; }
        public string National_Code { get; set; }
        public string Gender { get; set; }
        public string IsLogin { get; set; }
    }
}
