//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambulance_service
    {
        public int AS_id { get; set; }
        public Nullable<System.TimeSpan> AS_time { get; set; }
        public Nullable<System.DateTime> AS_date { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> Amb_id { get; set; }
        public Nullable<int> Driver_id { get; set; }
    }
}
