//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appoinment
    {
        public int Ap_id { get; set; }
        public Nullable<System.TimeSpan> Ap_time { get; set; }
        public Nullable<System.DateTime> Ap_date { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> DID { get; set; }
        public Nullable<int> Rcp_id { get; set; }
    }
}
