//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Bill_ID { get; set; }
        public Nullable<int> Bill_Total { get; set; }
        public string Bill_purpose { get; set; }
    }
}
