//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int DID { get; set; }
        public string Doc_name { get; set; }
        public string Doc_Lname { get; set; }
        public string PhoneNumber { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string NationalCode { get; set; }
        public string Specialization { get; set; }
        public Nullable<System.DateTime> Employment_date { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string IsLogin { get; set; }
    }
}
