//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugstore_cashier
    {
        public int DSC_id { get; set; }
        public string DSC_name { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string DSC_number { get; set; }
        public string Working_shift { get; set; }
        public Nullable<int> DS_id { get; set; }
    }
}
