//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int Mdcn_ID { get; set; }
        public string Mdcn_Name { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> m_date { get; set; }
        public Nullable<System.DateTime> e_date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Number1 { get; set; }
    }
}
