//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        public int NID { get; set; }
        public string Nurse_name { get; set; }
        public string Nurse_Lname { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public string National_Code { get; set; }
        public string Gender { get; set; }
        public string Marrige { get; set; }
        public Nullable<System.DateTime> Employment_date { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Shift { get; set; }
    }
}
