//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int op_id { get; set; }
        public Nullable<System.DateTime> op_date { get; set; }
        public Nullable<System.TimeSpan> op_time { get; set; }
        public Nullable<int> op_room_number { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> DID { get; set; }
    }
}
