//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PID { get; set; }
        public string Patient_Name { get; set; }
        public string Disease_type { get; set; }
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        public string Phone_Number { get; set; }
        public string Blood_Type { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Height { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
    }
}
