//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        public int prs_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public Nullable<int> PID { get; set; }
        public Nullable<int> DID { get; set; }
        public Nullable<int> Mdcn_ID { get; set; }
        public Nullable<int> Numbers { get; set; }
        public Nullable<int> NumberInDay { get; set; }
    }
}
