//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptionist
    {
        public int Rcp_id { get; set; }
        public string RcpName { get; set; }
        public string RcpLname { get; set; }
        public string gender { get; set; }
        public string national_code { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string isLogin { get; set; }
    }
}
