//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RID { get; set; }
        public Nullable<int> Room_number { get; set; }
        public string type { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    }
}
