//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class security
    {
        public int sec_ID { get; set; }
        public string sec_name { get; set; }
        public string sec_Lname { get; set; }
        public string sec_number { get; set; }
        public Nullable<System.TimeSpan> Working_time { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string national_code { get; set; }
    }
}
