//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class servant
    {
        public int servant_id { get; set; }
        public string servant_name { get; set; }
        public string servant_Lname { get; set; }
        public string servant_number { get; set; }
        public Nullable<System.TimeSpan> Working_time { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
