//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int Test_id { get; set; }
        public string Test_name { get; set; }
        public Nullable<System.DateTime> Test_date { get; set; }
        public Nullable<decimal> Test_cost { get; set; }
        public Nullable<System.DateTime> Reply_date { get; set; }
    }
}
