//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warrant
    {
        public int WID { get; set; }
        public Nullable<int> Base_Salary { get; set; }
        public Nullable<System.DateTime> Reg_Date { get; set; }
        public Nullable<System.DateTime> LastChange { get; set; }
        public Nullable<int> Premium { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<System.DateTime> Premium_Sdate { get; set; }
        public Nullable<System.DateTime> Premium_Fdate { get; set; }
    }
}
